### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by chrisgorgo** [wiheto/fetchopenfmri#1]
```
$ fetchopenfmri.exe 114 ~/Downloads/
Downloading: ds000114_R2.0.1_raw.zip
--- Download complete ---
Uncompressing: ds000114_R2.0.1_raw.zip
--- Uncompressing complete ---
Clean up. Deleting: ds000114_R2.0.1_raw.zip
Traceback (most recent call last):
  File "c:\users\filo\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\filo\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\filo\Anaconda3\Scripts\fetchopenfmri.exe\__main__.py", line 9, in <module>
  File "c:\users\filo\anaconda3\lib\site-packages\fetchopenfmri\fetch.py", line 18, in main
    get_dataset(sys.argv[1],sys.argv[2])
  File "c:\users\filo\anaconda3\lib\site-packages\fetchopenfmri\fetch.py", line 91, in get_dataset
    os.remove(datasetDir+f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/filo/Downloads//openfmri/ds000114_R2.0.1_raw.zip'
```

**Comment by wiheto** [comment]
So I have added `ZipFile.close()` (and corresponding close statement for TarFile) which I think was causing the problem here (trying to delete a zip file that was already opened). 

Could you tell me if it is working for you now? If you don't have time, I will be able to test it next week.

**Comment by wiheto** [comment]
From my testing, everything seems to be fine now.
